set_global_assignment -name RESERVE_ALL_UNUSED_PINS "AS INPUT TRI-STATED"
set_location_assignment PIN_60 -to LED7[7]
set_location_assignment PIN_59 -to LED7[6]
set_location_assignment PIN_58 -to LED7[5]
set_location_assignment PIN_57 -to LED7[4]
set_location_assignment PIN_31 -to LED7[3]
set_location_assignment PIN_30 -to LED7[2]
set_location_assignment PIN_14 -to LED7[1]
set_location_assignment PIN_15 -to LED7[0]
set_location_assignment PIN_28 -to key_data[0]
set_location_assignment PIN_24 -to key_data[1]
set_location_assignment PIN_27 -to key_data[2]
set_location_assignment PIN_130 -to key_data[3]
set_location_assignment PIN_129 -to key_data[4]