set_global_assignment -name RESERVE_ALL_UNUSED_PINS "AS INPUT TRI-STATED"
set_location_assignment PIN_60 -to LED7[7]
set_location_assignment PIN_59 -to LED7[6]
set_location_assignment PIN_58 -to LED7[5]
set_location_assignment PIN_57 -to LED7[4]
set_location_assignment PIN_31 -to LED7[3]
set_location_assignment PIN_13 -to LED7[2]
set_location_assignment PIN_14 -to LED7[1]
set_location_assignment PIN_15 -to LED7[0]
set_location_assignment PIN_86 -to switch[0]
set_location_assignment PIN_87 -to switch[1]
set_location_assignment PIN_88 -to switch[2]
set_location_assignment PIN_89 -to switch[3]
set_location_assignment PIN_90 -to switch[4]
set_location_assignment PIN_92 -to switch[5]
set_location_assignment PIN_94 -to switch[6]
set_location_assignment PIN_95 -to switch[7]
